Foreground true
TCPSocket 3310
TCPAddr 0.0.0.0
User clamav
DatabaseDirectory /var/lib/clamav
StreamMaxLength 5000M
MaxFileSize 5000M
MaxScanSize 5000M
MaxScanTime 600000
AlertExceedsMax yes
LogTime yes
